// const score=400;
// console.log(score);
// const balance=new Number(100);
// console.log(balance);
// console.log(balance.toString().length);
// console.log(typeof(balance));
// console.log(balance.toFixed(2));
// const othernumber=23.3553;
// console.log(othernumber.toPrecision(2));
// const hundered=100000;
// console.log(hundered.toLocaleString('en-IN'));
// // console.log(max(12,56));
// const x=new Number(122);
// console.log(Math.max(12,65));
//***************************math************************************ */
// console.log(Math);
// console.log(Math.abs(-4));
// console.log(Math.round(4.3));
// console.log(Math.ceil(4.3));
// console.log(Math.floor(4.3));
// console.log(Math.sqrt(3));
// console.log(Math.max(12,53,2,46));
// console.log(Math.random());
// console.log((Math.random()*10)+1);
const min=10;
const max=20;
console.log(Math.floor(Math.random()*(max-min+1)+min));