let value=3;
let negvalue=-value;
console.log(negvalue);
console.log(2+2);
console.log(2*2);
console.log(2%2);
console.log(2**2);
let str1="rahul";
let str2="Kumar";
console.log(str1+str2);
console.log(typeof(1+"2"+2));
console.log(typeof("1"+2+2));
console.log("1"+2+2);